### ISSUE TITLE
Implement persistent volume support

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-kubernetes-provider#14]
CloudStack can create, destroy, attach and detach persistent volumes to nodes in the form of data disks on primary storage.

These can be used as persistent volumes in Kubernetes, with some limitations:
- A data disk can only be attached to one node at a time. This limits the Access Type to `ReadWriteOnce`.
- Data disks need to be assigned a disk offering at creation time, which must exist in CloudStack and allow specifying a custom size. The offering should be selectable via the Storage Class.

The CCM framework currently contains an interface for fetching Labels for Persistent Volumes, but it is not entirely clear how this integrates with a cloud provider. It may be necessary to implement a separate storage provisioner. This provisioner could be standalone or interface with the cloud provider.

**Comment by joschi36** [comment]
There is now CSI driver for CloudStack. Do you think we can close this issue? https://github.com/apalia/cloudstack-csi-driver
