### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by iamcryptoki** [apache/cloudstack-kubernetes-provider#15]
Hello!

Is this project still maintened?

**Comment by DaanHoogland** [comment]
@iamcryptoki , i think there is still interest but i have no idea who the leading developers are.this was migrated from kuvbernetes to the cloudstack project to prevent it from being deleted completely. Are you volunteering?

**Comment by iamcryptoki** [comment]
Thank you for your reply!

Not at the moment but I would be more than happy to volunteer in the very near future if the project is no longer maintained.

**Comment by rhtyd** [comment]
@iamcryptoki any help and volunteering is welcome!

**Comment by onitake** [comment]
@iamcryptoki Thanks for the offer!
The project is very much alive, but still needs some love from a few sides.

If you have any issues, input or pull requests, please post them on the Github tracker.

And if you want to try the provider for yourself, you can always build it locally.
I recommend merging #8 , #10 , #11 and #9 as they contain various fixes and the IP whitelisting feature that I just finished. Any feedback on #9 is highly appreciated.

**Comment by onitake** [comment]
@iamcryptoki You can also take a look at https://hub.docker.com/repository/docker/swisstxt/cloudstack-kubernetes-provider - I'm occasionally pushing development versions there.

**Comment by onitake** [comment]
Release management and CI is being addressed in #7  and #16 .
We have access to Dockerhub now, and containers will be pushed there.

Please stay tuned for the v1.0 release.

**Comment by rhtyd** [comment]
Closing this, @iamcryptoki pl follow #7 and #16  and wait for v1.0 something soon (in coming weeks/months).
