### ISSUE TITLE
[DISCUSS] Work on next release

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-kubernetes-provider#16]
We now have capability to push container builds on `apache` dockerhub org. This issue/thread is to discuss:

- what needs to be tested, how?
- documentation on usage etc.
- timeline for the next release
- milestone, release management

This is largely something that's not clear, any takes - @onitake maybe?

**Comment by onitake** [comment]
Thank you, @rhtyd !

IMHO, testing should largely be done through unit tests.
At the moment, there are only a few of them, and they depend on a working CloudStack environment, or a mockup thereof.
So, I would suggest that we construct a test environment with a mocked ACS management server, then run a `go test -v` inside, with environment vars set so it can connect to the mock.
These tests can then be further extended through checks against the server, if all requested resources were deployed correctly.

As for the documentation, the README should be sufficient to get the provider running, but it's not very extensive.

The other questions are a bit more on the management side, but I would suggest we adopt best practices from the container world. Frequent, independent releases, the `latest` tag should always point to the latest stable release, example deployments should point to a particular version and only use features therein, etc.

**Comment by onitake** [comment]
It may also be a good idea to look at what others are doing:
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

**Comment by rhtyd** [comment]
Ping - @onitake any update on this, how can the community help?

**Comment by rhtyd** [comment]
ping @onitake - pl advise whenever it's ready for the next release? Thanks

**Comment by onitake** [comment]
@rhtyd I think we are ready to cut a release when CI is set up and the outstanding issues are fixed (i.e. #19 , #18 , #17 )

The version we're running in production is equivalent to what's in the source tree right now, and it's working very well.

Should I prepare a changelog with respect to the initial source drop? Or a full "initial release" note?

**Comment by onitake** [comment]
Going through all the issues, there is another thing we might want to consider, but I'm not sure if it should be done for 1.0:

We're building against an older version of the k8s framework (1.15.2), and Kubernetes is already at 1.19. The Kubernetes project guarantees compatibility +/- two version steps, so we may already have issues with 1.19. But I currently don't have a way to test this.

If you're ok with it, I think we should release 1.0 built against the old framework, as that's what we tested with.
Post-1.0 we should fix #20 and #13. The k8s project recommends to always build against the latest framework code, so we may want to regularly update frameworks and test against different cluster versions.

**Comment by davidjumani** [comment]
@onitake I can look into https://github.com/apache/cloudstack-kubernetes-provider/issues/20 if you're not already on it

**Comment by onitake** [comment]
@davidjumani Yes, please go ahead!

**Comment by rhtyd** [comment]
@onitake re-ping, any plans on helping with a release? What PRs should we fix? Unfortunately, I don't know how to use/test this.

**Comment by rhtyd** [comment]
I checked there no outstanding issues/PR on the v1.0 milestone - https://github.com/apache/cloudstack-kubernetes-provider/milestone/1

**Comment by rhtyd** [comment]
Ping @onitake cc @davidjumani @gsirett

**Comment by davidjumani** [comment]
+1 Tested and working on v1.16+

**Comment by rhtyd** [comment]
Ping @onitake (work on next release) ?

**Comment by onitake** [comment]
Sorry @rhtyd I haven't had much time to look at the the k8s provider lately.
Could you coordinate with @joschi36 instead?

I'll gladly contribute code when needed, though.

**Comment by joschi36** [comment]
Hi @rafaelweingartner 

For myself I would like to merge #25 to the release.

Maybe @davidjumani has interest in adding #24 and #22 to the release as well?

Also, I thought we don't have access to docker hub right now. https://github.com/apache/cloudstack-kubernetes-provider/issues/7
And there is also no CI in place for creating docker images.

I would love to take release management into my hands. However, it's hard to coordinate without the rights and missing pieces.

**Comment by rhtyd** [comment]
Hi @joschi36 thanks, we've https://hub.docker.com/r/apache/cloudstack-kubernetes-provider for releases and builds, I can help with release effort.

**Comment by davidjumani** [comment]
+1 for this release. It'll be good to get an official release out to get wider feedback and then decide how to proceed

**Comment by rhtyd** [comment]
@joschi36 @onitake @davidjumani - I see all PRs merged now, do we have anything outstanding for 1.0 release?

**Comment by joschi36** [comment]
I think we can release 1.0.0 now.

**Comment by davidjumani** [comment]
+1

**Comment by onitake** [comment]
I'm also for releasing 1.0.0.

One nitpick: Maybe change https://github.com/apache/cloudstack-kubernetes-provider/blob/master/deployment.yaml#L146 to `image: apache/cloudstack-kubernetes-provider:1.0.0" for the release? It should stay on `latest` for the master branch though.

**Comment by onitake** [comment]
Oh, I just noticed something incorrect in the readme: https://github.com/apache/cloudstack-kubernetes-provider/blame/master/README.md#L23
"DeamonSet" is actually wrong. There should only be a single instance of the provider. Here's a PR: #27

**Comment by joschi36** [comment]
What's the status here now?
Can we create the release now?

**Comment by rhtyd** [comment]
@onitake @joschi36 since this project is under ASF now, a committer or PMC member has right to publish source tarball and to dockerhub. I'll work with you both of you and with @davidjumani to figure out the build and release channels and start a RC1 voting soon (provide administrative assistance).

@davidjumani do you want to help as a co-RM? Longer-term you can help maintain the repo along with @onitake and @joschi36?

**Comment by rhtyd** [comment]
As the next steps, I've created a script that will help perform source releases (copied from other ACS repos):
https://github.com/apache/cloudstack-kubernetes-provider/blob/master/performrelease.sh

And I've built/pushed latest/master build here:
https://hub.docker.com/r/apache/cloudstack-kubernetes-provider/tags?page=1&ordering=last_updated

@onitake @joschi36 @davidjumani can you review and test above ^^ if the release via dockerhub works and there are no blockers, I'll help with admin work and start a discussion on k8s-provider v1.0 release on dev.

**Comment by davidjumani** [comment]
+1 for co-RM and maintaining with @onitake and @joschi36

**Comment by onitake** [comment]
@rhtyd Your script pushes the source tarballs to a Subversion repository - is that standard practice in the Apache foundation?
I'd thought that nobody uses Subversion any more. :smile: 

I suppose repackaging makes sense, as the the Github source archive service only provides zip and tar.gz files, and no checksums.
So the script looks ok to me - although I haven't tested it as I don't have access to that svn repo.

How will it be executed? I suppose we need to modify `.travis.yml` - @davidjumani you proposed changes to that and the Makefile in #30 , can you submit a PR with the proposed changes so we can discuss the CI build? Thanks!

**Comment by joschi36** [comment]
@rhtyd I have tested the release, and it seems working.

**Comment by davidjumani** [comment]
@onitake @joschi36 @rhtyd Since there are no more issues / PRs for v1.0, Shall we cut a release ?

**Comment by davidjumani** [comment]
Ping @rhtyd @onitake @joschi36 shall I take it as an overwhelmingly yes ?

**Comment by rhtyd** [comment]
+1, if @onitake and @joschi36 don't respond, I would say let's do some basic smoke-testing to ensure it is working and cut RC.

**Comment by rhtyd** [comment]
@davidjumani I've created/pushed latest build to https://hub.docker.com/r/apache/cloudstack-kubernetes-provider/tags?page=1&ordering=last_updated

When you've time please run some tests and also send a doc PR to (add a new entry) https://github.com/apache/cloudstack-documentation/tree/main/source/plugins on how users can use this.

**Comment by onitake** [comment]
+1 to release.

I'll take a look at it @rhtyd .

**Comment by rhtyd** [comment]
Thanks @onitake please advise if the current build/main is stable to cut RC cc @davidjumani

**Comment by davidjumani** [comment]
Tested, works as expected. Will cut an RC next week and a release once :
https://github.com/apache/cloudstack-kubernetes-provider/pull/35
https://github.com/apache/cloudstack-documentation/pull/233
https://github.com/apache/cloudstack/pull/5254
are merged

**Comment by davidjumani** [comment]
@onitake @joschi36 Can you review the related PRs ? Thanks

**Comment by rhtyd** [comment]
Discussed with @davidjumani the first two PRs are merged and https://github.com/apache/cloudstack/pull/5254 is in a different repository which will be tracked under 4.16.0.0 milestone and does not hold the v1.0 milestone of acs-k8s-provider. Closing the issue as we're in a position now to cut the first RC once/when the RM finds suitably.

**Comment by rhtyd** [comment]
@onitake @joschi36 David has started a vote thread here - https://markmail.org/message/nehouswgefdxe3kj Please help test the RC and vote. Hopefully, we'll see our first ever v1.0 soon.
