### ISSUE TITLE
Fix License headers to files

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack-kubernetes-provider#19]
I see many scripts and go files don't have the Apache license header, we need to fix that. cc @onitake

**Comment by onitake** [comment]
I'll take care of it.

A few question with respect to [the policy](https://www.apache.org/legal/src-headers.html):
- Should I add a license header to Makefile and Dockerfile?
- go.mod is at least partially autogenerated by Go. Does it need a license header?
- go.sum is fully autogenerated, I don't think a license header is required (or makes even sense) there
- What about the example manifests deployment.yaml and nginx-ingress-controller-patch.yml?

Anything else I forgot?
