### ISSUE TITLE
Submit request to integrate into Kubernetes documentation

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-kubernetes-provider#5]
Now that transfer to the ASF is complete, the project should be submitted to be advertised as the "official" CloudStack provider for Kubernetes.

A PR on the k8s documentation is prepared:
See https://github.com/kubernetes/website/issues/14817 and https://github.com/kubernetes/website/pull/15509

**Comment by onitake** [comment]
I reopened the pull request, but we're still missing CI and built containers.
Without containers available on a public registry, kubernators won't be able to use the provider.

I think you should also consider creating a first release, and also update the deploy.yaml manifest accordingly.

@rhtyd As a short-term solution, you could simply push the Github repo to https://hub.docker.com/u/apache (provided that you have access).

**Comment by rhtyd** [comment]
Can you start a discussion thread on dev@ ML on this @onitake we'll have to check if anyone has any access to the orgs.

**Comment by onitake** [comment]
This was already fixed by https://github.com/kubernetes/website/pull/16129 - we can close this issue now.
