### ISSUE TITLE
LB IP cannot be created when Kubernetes is in VPC

### ISSUE THREAD

**Issue by mierea** [apache/cloudstack-kubernetes-provider#53]
The issue and a dirty workaround can be found here: https://github.com/apache/cloudstack/issues/8178

In short: kubernetes clusters can be started in vpc networking in cloudstack but the ccm is unaware of this and tries to add firewall rules. (but the firewall service is not available in vpc as vpc's use network acls instead)

**Comment by FilipBB** [comment]
I ran into this as well, thank you for the workaround @mierea

**Comment by weizhouapache** [comment]
@mierea 
this should have been fixed by #56
