### ISSUE TITLE
Continuous integration (Dockerhub, etc.) needed

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-kubernetes-provider#7]
On the old CCM, we manually pushed releases to DockerHub for building and hosting:
https://hub.docker.com/r/swisstxt/cloudstack-cloud-controller-manager/

To make the new provider available to the general public, it should have automatic CI attached, so it can be used in Kubernetes deployments.

The included Dockerfile is prepared to do all the grunt work already and shouldn't require many changes.

**Comment by onitake** [comment]
There is an apache user on Docker hub: https://hub.docker.com/u/apache
Do you have access there?

**Comment by rhtyd** [comment]
@onitake I don't think I've access there. Can you ask on the CloudStack dev ML? And maybe also access to the following org:
https://hub.docker.com/u/apachecloudstack
https://hub.docker.com/u/cloudstack

Alternatively, we can create a new organization.

**Comment by onitake** [comment]
@rhtyd Was there a followup on the mailing list? I think it got lost...
We definitely need a registry for storing prebuilt containers before we release 1.0, or people will have to build the controller themselves.

An alternative would be [Github Packages](https://github.com/features/packages), but Docker Hub is probably better.

**Comment by rhtyd** [comment]
We've the official account here now https://hub.docker.com/r/apache/cloudstack-kubernetes-provider
But only committers/PMC members have access.

**Comment by rhtyd** [comment]
Closing this dockerhub and travis are available.
